version: '2.1'

services:
  chrome:
    image: selenium/node-chrome:4.1.3-20220405
    shm_size: 2gb
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "6900:5900"

  hub:
    image: selenium/hub:latest
    container_name: hub
    restart: on-failure
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    
  webtric:
    container_name: webtric
    build:
      context: .
    restart: on-failure
    command: ["./wait-for-it.sh", "localhost:4444", "--", "./scripts/quotes.sh"]

  jupyter:
    image: jupyter/datascience-notebook:latest
    environment:
      - JUPYTER_TOKEN=webtric
    container_name: jupyter
    ports:
      - 8888:8888