version: '2.1'

services:
  hub:
    image: selenium/hub:latest
    container_name: hub
    restart: on-failure
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:latest
    restart: on-failure
    environment:
      HUB_PORT_4444_TCP_ADDR: localhost
      HUB_PORT_4444_TCP_PORT: 4444
    
  # webtric:
  #   container_name: webtric
  #   build:
  #     context: .
  #   restart: on-failure
  #   volumes:
  #     - .:/app
  #   command: ["./wait-for-it.sh", "http://localhost:4444/", "--", "./scripts/quotes.sh"]

  jupyter:
    image: jupyter/datascience-notebook:latest
    environment:
      - JUPYTER_TOKEN=webtric
    container_name: jupyter
    ports:
      - 8888:8888